In [3]:
from sklearn.datasets import load_wine
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

data_w = load_wine()['data']
target_w = load_wine()['target']
cls = KNeighborsClassifier(n_neighbors=3)

clNB = GaussianNB()


In [4]:
type(data_w)

numpy.ndarray

In [5]:
train_w, test_w, target_train_w, target_test_w = train_test_split(data_w, target_w, test_size=0.25, random_state=0)

In [52]:
# Wine
cls = cls.fit(train_w, target_train_w)
####
clNB = clNB.fit(train_w, target_train_w)

In [53]:
print('K-N', confusion_matrix(cls.predict(test_w), target_test_w))
print()
print("Bayes' Analysis")
print(confusion_matrix(clNB.predict(test_w), target_test_w))
matrix = confusion_matrix(clNB.predict(test_w), target_test_w)

K-N [[14  1  4]
 [ 1 18  3]
 [ 1  2  1]]

Bayes' Analysis
[[16  2  0]
 [ 0 18  0]
 [ 0  1  8]]


In [54]:
print('Accuracy {:.2f}'.format((matrix[0][0]+matrix[1][1]+matrix[2][2])/len(test_w) * 100))

Accuracy 93.33


In [55]:
(14+18+1)/45, (16+18+8)/45

(0.7333333333333333, 0.9333333333333333)

In [56]:
train_cv_w, test_cv_w, target_cv_train_w, target_cv_test_w = train_test_split(train_w, target_train_w, test_size=0.25, random_state=0)

In [57]:
cls1 = KNeighborsClassifier(n_neighbors=3)
cls1=cls1.fit(train_cv_w, target_cv_train_w)
####clNB
clNB = GaussianNB()
clNB = clNB.fit(train_cv_w, target_cv_train_w)

In [59]:
# confusion_matrix(cls1.predict(test_cv_w), target_cv_test_w)

print('K-N', confusion_matrix(cls1.predict(test_cv_w), target_cv_test_w))
print()
matrix1 = confusion_matrix(clNB.predict(test_cv_w), target_cv_test_w)
print('Bayes CV Analysis')
print(matrix1)
print('Accuracy {:.2f}'.format((matrix1[0][0]+matrix1[1][1]+matrix1[2][2])/len(test_cv_w) * 100))

K-N [[ 8  4  2]
 [ 1 10  1]
 [ 0  6  2]]

Bayes CV Analysis
[[ 9  1  0]
 [ 0 19  0]
 [ 0  0  5]]
Accuracy 97.06


In [12]:
(8+10+2)/len(test_cv_w), (9+19+5)/len(test_cv_w) 

(0.5882352941176471, 0.9705882352941176)

In [13]:
# confusion_matrix(cls1.predict(test_w), target_test_w)

print('K-N', confusion_matrix(cls1.predict(test_w), target_test_w))
print('bayes',  confusion_matrix(clNB.predict(test_w), target_test_w))

K-N [[14  1  3]
 [ 0 18  3]
 [ 2  2  2]]
bayes [[16  2  0]
 [ 0 18  0]
 [ 0  1  8]]


In [64]:
(14+18+2)/len(test_w), (16+18+8)/len(test_w)
matrix2 = confusion_matrix(clNB.predict(test_w), target_test_w)
print('Bayes Analysis')
print(matrix2)
print('Accuracy {:.2f}'.format((matrix2[0][0]+matrix2[1][1]+matrix2[2][2])/len(test_w) * 100))

Bayes Analysis
[[16  2  0]
 [ 0 18  0]
 [ 0  1  8]]
Accuracy 93.33


In [6]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
clg = KNeighborsClassifier(n_neighbors=3)
clNBm = GaussianNB()
kfold = KFold(n_splits=10)

In [13]:
for train_index, test_index in kfold.split(train_w):
    X_train, X_test = train_w[train_index], train_w[test_index]
    y_train, y_test = target_train_w[train_index], target_train_w[test_index]
    
    clg = clg.fit(X_train, y_train)
    clNBm = clNBm.fit(X_train, y_train)
    
    y_pred = clg.predict(X_test)
    y_pred1 = clNBm.predict(X_test)
    
    matrix = confusion_matrix(y_test, y_pred)
    matrix1 = confusion_matrix(y_test, y_pred1)
    
    print('KN',((matrix[0][0]+matrix[1][1]+matrix[2][2])/len(X_test))*100)
    print('GB',((matrix1[0][0]+matrix1[1][1]+matrix1[2][2])/len(X_test))*100)

KN 57.14285714285714
GB 100.0
KN 42.857142857142854
GB 85.71428571428571
KN 71.42857142857143
GB 100.0
KN 69.23076923076923
GB 100.0
KN 69.23076923076923
GB 100.0
KN 76.92307692307693
GB 100.0
KN 69.23076923076923
GB 100.0
KN 84.61538461538461
GB 100.0
KN 53.84615384615385
GB 92.3076923076923
KN 76.92307692307693
GB 92.3076923076923


In [14]:
pred = clg.predict(test_w)
pred1 = clNBm.predict(test_w)

In [15]:
confusion_matrix(target_test_w, pred), print(confusion_matrix(target_test_w, pred1)) 

[[16  0  0]
 [ 1 19  1]
 [ 0  0  8]]


(array([[14,  1,  1],
        [ 1, 16,  4],
        [ 3,  3,  2]]), None)

In [16]:
(14+16+2)/len(target_test_w)

0.7111111111111111

In [17]:
accuracy = (16+19+8)/len(target_test_w) * 100
print("Accuracy on test set: {:.2f}".format(accuracy))

Accuracy on test set: 95.56


In [25]:
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.datasets import load_breast_cancer
# from sklearn.model_selection import KFold, train_test_split
# from sklearn.metrics import confusion_matrix

# data = load_breast_cancer()['data']
# target = load_breast_cancer()['target']

# cls = KNeighborsClassifier(n_neighbors=3)
# train, test, target_train, target_test = train_test_split(data, target, test_size=0.25, random_state=0)
# train_cv_w, test_cv_w, target_cv_train_w, target_cv_test_w = train_test_split(train, target_train, test_size=0.25, random_state=0)

# cls = cls.fit(train_cv_w, target_cv_train_w)
# result = cls.predict(test_cv_w)

# accuracy = confusion_matrix(target_cv_test_w, result)
# accuracy = (accuracy[0][0]+accuracy[1][1])/len(target_cv_test_w)
# accuracy = accuracy*100

# print("Cross Validated Accuracy: {:.2f}".format(accuracy))

# final_result = cls.predict(test)
# accuracy = confusion_matrix(target_test, final_result)
# accuracy = (accuracy[0][0]+accuracy[1][1])/len(target_test)
# accuracy = accuracy*100
# print("Accuracy on test set: {:.2f}".format(accuracy))

print('For KFold Validation')
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

data = load_breast_cancer()['data']
target = load_breast_cancer()['target']

clg = KNeighborsClassifier(n_neighbors=3)
train, test, target_train, target_test = train_test_split(data, target, test_size=0.25, random_state=0)
kfold = KFold(n_splits=10)

for train_index, test_index in kfold.split(train):
    X_train, X_test = train[train_index], train[test_index]
    y_train, y_test = target_train[train_index], target_train[test_index]
    
    clg = clg.fit(X_train, y_train)
    
    y_pred = clg.predict(X_test)
    
    matrix = confusion_matrix(y_test, y_pred)
    
    print('KN',((matrix[0][0]+matrix[1][1])/len(X_test))*100)

    
matrix1 = confusion_matrix(target_test,clg.predict(test))    
accuracy = (matrix1[0][0]+matrix1[1][1])/len(target_test)
accuracy = accuracy*100
print("Accuracy on test set: {:.2f}".format(accuracy))


For KFold Validation
KN 93.02325581395348
KN 95.34883720930233
KN 86.04651162790698
KN 88.37209302325581
KN 88.37209302325581
KN 90.69767441860465
KN 92.85714285714286
KN 90.47619047619048
KN 95.23809523809523
KN 95.23809523809523
Accuracy on test set: 93.01
